theme: dark

server:
  address: 'tcp://:$AUTHELIA_PORT'
  endpoints:
    authz:
      forward-auth:
        implementation: "ForwardAuth"
  buffers:
    read: 4096
    write: 4096

log:
  level: 'debug'
  format: 'text'
  file_path: '/config/authelia.log'
  keep_stdout: false

totp:
  issuer: 'authelia.com'

identity_validation:
  reset_password:
    jwt_secret: $AUTHELIA_JWT_SECRET

authentication_backend:
  file:
    path: '/config/users_database.yml'

session:
  secret: $AUTHELIA_SESSION_SECRET

  cookies:
    - name: 'authelia_session'
      domain: '$DOMAINNAME'  # Should match whatever your root protected domain is
      authelia_url: 'https://$AUTHELIA_PREFIX.$DOMAINNAME/'
      expiration: '24 hour'
      inactivity: '1 hour'
      default_redirection_url: 'https://$HOMEPAGE_PREFIX.$DOMAINNAME/'
      
regulation:
  max_retries: 10
  find_time: '2 minutes'
  ban_time: '3 minutes'

storage:
  encryption_key: '$AUTHELIA_STORAGE_ENCRYPTION_KEY'
  local:
    path: '/config/db.sqlite3'

notifier:
  filesystem:
    filename: '/config/notification.txt'

access_control:
  
  default_policy: 'one_factor'
  rules:

    # Bypass Authelia to prevent redirect loop
    - domain: $AUTHELIA_PREFIX.$DOMAINNAME
      policy: bypass
      
#    - domain: $VW_PREFIX.$DOMAINNAME
#      resources:
#        - "^/api.*$"
#      policy: bypass
#     
#    - domain: openldap.$DOMAINNAME
#      policy: bypass 

    # Bypass Login for Media Servers
#    - domain: jellyfin.$DOMAINNAME
#      policy: bypass

#    - domain: jellyseerr.$DOMAINNAME
#      policy: bypass

#    - domain: kavita.$DOMAINNAME
#      policy: bypass

#    - domain: navidrome.$DOMAINNAME
#      policy: bypass

    # - domain: "*" # Bypass auth on local network and localhost
    #   policy: bypass
    #   networks:
    #     - 192.168.1.0/24
    #     - 0.0.0.0/24

    # Add more rules here, to use a login screen use one_factor
