"""
This script builds the configurations for Traefik/Authelia/Homepage
It is run as part of ./compose-up.sh ./network-up.sh but can be run independently

Uses the following files to source the configuration:
 - ./.env
 - ./config.json or ./config.py 

Applies configuration to the following files:
 - ${CONFIGDIR}/traefik/traefik.yml
 - ${CONFIGDIR}/traefik/dynamic-config.yml
 - ${CONFIGDIR}/authelia/users_database.yml
 - ${CONFIGDIR}/authelia/configuration.yml
 - ${CONFIGDIR}/homepage/services.yaml

Should always be run with sudo
"""

import os
import json
from importlib.util import spec_from_loader, module_from_spec
from importlib.machinery import SourceFileLoader 

if os.path.exists("config.json"):
  with open("config.json") as f:
    config = json.load(f)
  routes = config["routes"]
  custom_descriptions = config["descriptions"]
  layout = config["layout"]
else:
  from config import layout, routes, descriptions as custom_descriptions

# Loads environement variables from .env file
spec = spec_from_loader("env", SourceFileLoader("env", os.path.abspath("./.env")))
spec.loader.exec_module(env := module_from_spec(spec))
# Load all upper-case constants
env_map = {k:v for k,v in env.__dict__.items() if k==k.upper()}
domainname = env.DOMAINNAME
config_dir = env.CONFIGDIR

# Built-in route descriptions
descriptions = {
  # "prefix" : "description",
  "adguard": "Home AD Blocking DNS",
  "bazarr": "Bazarr (Subtitle Requester) Web UI",
  "filebot": "Video File Manager",
  "filebrowser":"Consolidated Media File Browser",
  "homeassistant": "Home Automation Service",
  "jackett":"Torrent Indexer",
  "jellyfin": "Video/Music Player",
  "jellyseerr":"Show and Movie Requester",
  "lidarr": "Music Downloader",
  "kavita": "Ebook Reader",
  "navidrome": "Music Player / Server",
  "nzbhydra":"Torrent Indexer",
  "picard": "Music File and Metadata Manager",
  "portainer": "Docker Container Manager",
  "qbittorrent":"Torrent Downloader",
  "radarr":"Movie Requester",
  "readarr":"Book Requester",
  "sonarr":"Show Requester",
  "traefik": "Traefik Dashboard",
  "whatsup": "Docker Container Update Manager",
  "youtubedl": "YouTube Downloader",
  "it-tools": "IT/Net/Dev/Converter Toolbox",
}
descriptions.update(custom_descriptions)

# Make traefik configuration traefik.yml
warning = f"""
# GENERATED BY apply_config.py
# MAKE CHANGES IN .env & config.py/config.json
"""

# Traefik Dynamic File Configuration
config = f"""{warning}
tls:
  options:
    modern:
      minVersion: "VersionTLS13"
    intermediate:
      minVersion: "VersionTLS12"
      cipherSuites:
        - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
        - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
        - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305"
        - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
        - "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256"
        - "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256"
        - "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA"
        - "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA"
        - "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA"
        - "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA"
        - "TLS_RSA_WITH_AES_128_GCM_SHA256"
        - "TLS_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_RSA_WITH_AES_128_CBC_SHA256"
        - "TLS_RSA_WITH_AES_128_CBC_SHA"
        - "TLS_RSA_WITH_AES_256_CBC_SHA"
        - "TLS_RSA_WITH_3DES_EDE_CBC_SHA"

http:
  middlewares:
    # Security headers
    securityHeaders:
      headers:
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex"
          X-Forwarded-Proto: "https"
          server: ""
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        sslProxyHeaders:
          X-Forwarded-Proto: "https"
        referrerPolicy: "same-origin"
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        contentTypeNosniff: true
        browserXssFilter: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 63072000
        stsPreload: true
  ## TRANSPORTS ##
  serversTransports:
    insecureTransport:
      insecureSkipVerify: true
"""

routes.extend([
])

# Make traefik dynamic config
routers = "  routers:\n"
services = "  services:\n"
for host, url, insecure, tls_config in routes:
  if host == "#": continue # Skip section headers
  routers += f"""
    {host}:
      entryPoints:
        - https
      rule: 'Host(`{host}.{domainname}`)'
      service: {host}
      tls:
        options: {tls_config}@file
"""
  transport = "serversTransport: insecureTransport" if insecure else ""
  services += f"""
    {host}:
      loadBalancer:
        {transport}
        servers:
          - url: {url}
"""
with open(f"{config_dir}/traefik/dynamic-config.yml", "w+") as f:
  f.write(config + routers + services)

# Make authelia users_database.yml if it doesn't exist
if not os.path.exists(f"{config_dir}/authelia/users_database.yml"):
  usersdb = f"""
users:
  {env_map.get('AUTHELIA_ADMIN_USERNAME')}:
    disabled: false
    displayname: "{env_map.get('AUTHELIA_ADMIN_USERNAME')}"
    password: "{env_map.get('AUTHELIA_ADMIN_PASSWORD_HASH')}"
    email: {env_map.get('AUTHELIA_ADMIN_EMAIL')}
    groups:
      - admins
      - dev
  {env_map.get('AUTHELIA_USER_USERNAME')}::
    disabled: false
    displayname: "{env_map.get('AUTHELIA_USER_USERNAME')}"
    password: "{env_map.get('AUTHELIA_USER_PASSWORD_HASH')}"
    email: {env_map.get('AUTHELIA_USER_EMAIL')}
    groups:
      - dev
"""
  with open(f"{config_dir}/authelia/users_database.yml", "w+") as f:
    f.write((warning + usersdb).replace("$$", "$"))

# Make authelia configration.yml
with open(f"{config_dir}/authelia/configuration-template.yml") as f:
  template = f.read()
for k, v in env_map.items():
  template = template.replace(f"${k}" ,v)
with open(f"{config_dir}/authelia/configuration.yml", "w+") as f:
  f.write(warning + template)

# Make traefik configuration traefik.yml
with open(f"{config_dir}/traefik/traefik-template.yml") as f:
  template = f.read()
for k, v in env_map.items():
  template = template.replace(f"${k}" ,v)
with open(f"{config_dir}/traefik/traefik.yml", "w+") as f:
  f.write(warning + template)

# Make dashboard config
dashboard = warning
for category, items in layout.items():
  dashboard += f"""
- \"{category}\":"""
  for name, prefix in items.items():
    dashboard += f"""
    - \"{name}\":
        href: https://{prefix}.{domainname}
        description: {descriptions.get(prefix)}
"""
with open(f"{config_dir}/homepage/services.yaml", "w+") as f:
  f.write(dashboard)