
networks:
  traefik_network:
    driver: bridge
    name: traefik_network
    external: true


volumes:
  audiobooks:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: '${AUDIOBOOKSDIR}'

  books:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: '${BOOKSDIR}'

  downloads:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: '${DOWNLOADSDIR}'

  movies:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: '${MOVIESDIR}'
  
  music:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: '${MUSICDIR}'

  photos:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: '${PHOTOSDIR}'

  shows:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: '${SHOWSDIR}'

  documents:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: '${DOCUMENTSDIR}'
  
  podcasts:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: '${PODCASTSDIR}'

services:
  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    environment:
      - PUID=1024
      - PGID=101
      - TZ=${TZ}
    networks:
      - traefik_network
    ports:
      - "${PORTAINER_PORT}:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${CONFIGDIR}/portainer:/data"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${DOMAINNAME}`)"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer.entrypoints=https"

  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    # devices: 
    #   - /dev/ttyUSB1
    #   - /dev/ttyUSB0
    networks:
      - traefik_network
    environment:
      - PUID=1024
      - PGID=101
      - TZ=${TZ}
    ports:
      - ${HOMEASSISTANT_PORT}:8123
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONFIGDIR}/homeassistant:/config
      - ${CONFIGDIR}/homeassistant/data:/mnt/Data
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homeassistant.rule=Host(`homeassistant.${DOMAINNAME}`) || Host(`ha.${DOMAINNAME}`)"
      - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"
      - "traefik.http.routers.homeassistant.entrypoints=https"

  whatsupdocker:
    image: fmartinou/whats-up-docker
    container_name: whatsupdocker
    networks:
      - traefik_network
    environment:
      - PUID=1024
      - PGID=101
      - TZ=${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONFIGDIR}/wud:/store
    ports:
      - ${WUD_PORT}:3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whatsupdocker.entrypoints=https"
      - "traefik.http.routers.whatsupdocker.rule=Host(`whatsupdocker.${DOMAINNAME}`)"
      - "traefik.http.services.whatsupdocker.loadbalancer.server.port=3000"

  it-tools:
    ports:
      - "${ITTOOLS_PORT}:80"
    container_name: it-tools
    networks:
      - traefik_network
    environment:
      - PUID=1024
      - PGID=101
      - TZ=${TZ}
    image: corentinth/it-tools
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.it-tools.entrypoints=https"
      - "traefik.http.routers.it-tools.rule=Host(`it-tools.${DOMAINNAME}`)"
      - "traefik.http.services.it-tools.loadbalancer.server.port=80"

  guacd:
    container_name: guac_guacd
    image: guacamole/guacd
    networks:
      - traefik_network
    environment:
      - TZ=${TZ}
    restart: unless-stopped
    volumes:
      - ${CONFIGDIR}/guacamole/guacd/drive:/drive:rw
      - ${CONFIGDIR}/guacamole/guacd/record:/record:rw

  postgres:
    container_name: guac_postgres
    networks:
      - traefik_network
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PGDATA=/var/lib/postgresql/data/guacamole
      - POSTGRES_DB=guacamole_db
      - POSTGRES_PASSWORD='${GUACAMOLE_POSTGRESS_PASSWORD}'
      - POSTGRES_USER='${GUACAMOLE_POSTGRESS_USER}'
    image: postgres:15.2-alpine
    volumes:
      - ${CONFIGDIR}/guacamole/postgress/init:/docker-entrypoint-initdb.d:z
      - ${CONFIGDIR}/guacamole/postgress/data:/var/lib/postgresql/data:Z
  
  guacamole:
    image: guacamole/guacamole
    container_name: guacamole
    depends_on:
      - guacd
      - postgres
    environment:
      - TZ=${TZ}
      - GUACD_HOSTNAME=guacd
      - POSTGRESQL_DATABASE=guacamole_db
      - POSTGRESQL_HOSTNAME=postgres
      - POSTGRESQL_PASSWORD='${GUACAMOLE_POSTGRESS_PASSWORD}'
      - POSTGRESQL_USER='${GUACAMOLE_POSTGRESS_USER}'
      - LDAP_HOSTNAME=openldap
      - LDAP_PORT=${OPENLDAP_PORT}
      - LDAP_USER_BASE_DN=ou=people,${LDAP_BASE_DN}
      - LDAP_GROUP_SEARCH_FILTER=CN=guacamoleusers,OU=groups,${LDAP_BASE_DN}
      - LDAP_SEARCH_BIND_DN=cn=admin,${LDAP_BASE_DN}
      - LDAP_SEARCH_BIND_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - LDAP_USERNAME_ATTRIBUTE=uid
      # - EXTENSION_PRIORITY=openid
      # - OPENID_CLIENT_ID=guacamole
      # - OPENID_SCOPE=openid profile groups email
      # - OPENID_ISSUER=https://${AUTHELIA_PREFIX}:443.${DOMAINNAME}
      # - OPENID_JWKS_ENDPOINT=https://${AUTHELIA_PREFIX}.${DOMAINNAME}/jwks.json
      # - OPENID_AUTHORIZATION_ENDPOINT=https://${AUTHELIA_PREFIX}.${DOMAINNAME}/api/oidc/authorization?state=1234abcedfdhf
      # - OPENID_REDIRECT_URI=https://guacamole.$DOMAINNAME
      # - OPENID_USERNAME_CLAIM_TYPE=preferred_username
      # - OPENID_GROUPS_CLAIM_TYPE=sub
      # - OPENID_ALLOWED_CLOCK_SKEW=99999
    links:
      - guacd
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.guacamole.entrypoints=https"
      - "traefik.http.routers.guacamole.rule=Host(`guacamole.$DOMAINNAME`)"
      - "traefik.http.routers.guacamole.middlewares=add-guacamole"
      - "traefik.http.middlewares.add-guacamole.addPrefix.prefix=/guacamole"
      - "traefik.http.services.guacamole.loadbalancer.server.port=8080"
    ports:
      - ${GUACAMOLE_PORT}:8080
    volumes:
      - ${CONFIGDIR}/authelia/keys:/certs:ro

  vaultwarden:
    image: vaultwarden/server:latest
    hostname: vaultwarden
    container_name: vaultwarden
    restart: unless-stopped
    networks:
      - traefik_network
    volumes:
      - ${CONFIGDIR}/vaultwarden/:/data
    # ports:
    #   - ${VAULTWARDEN_PORT}:80
    environment:
      - TZ=${TZ}
      - LOGIN_RATELIMIT_MAX_BURST=10
      - LOGIN_RATELIMIT_SECONDS=60
      - DOMAIN=https://$VW_PREFIX.$DOMAINNAME/
      - INVITATION_ORG_NAME=x
      - INVITATION_ALLOWED=${VW_SIGNUPS_ALLOWED}
      - ADMIN_TOKEN=${VW_ADMIN_TOKEN}
      - SIGNUPS_ALLOWED=false
      - EMERGENCY_ACCESS_ALLOWED=true
      - SENDS_ALLOWED=true
      - WEB_VAULT_ENABLE=true
      - WEBSOCKET_ENABLED=${VW_WEBSOCKET_ENABLED}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vaultwarden.entrypoints=https"
      - "traefik.http.routers.vaultwarden.rule=Host(`$VW_PREFIX.$DOMAINNAME`)"
      - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"

  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    hostname: kavita
    networks:
      - traefik_network
    environment:
      - PUID=1024
      - PGID=101
      - TZ=${TZ}
    ports:
      - ${KAVITA_PORT}:5000
    volumes:
      - "${CONFIGDIR}/kavita:/config"
      - "books:/data:ro"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kavita.rule=Host(`read.${DOMAINNAME}`) || Host(`kavita.${DOMAINNAME}`)"
      - "traefik.http.services.kavita.loadbalancer.server.port=5000"
      - "traefik.http.routers.kavita.entrypoints=https"

  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    hostname: navidrome
    networks:
      - traefik_network
    restart: unless-stopped
    ports:
      - ${NAVIDROME_PORT}:4533
    environment:
      -ND_SCANSCHEDULE: 1h
      -ND_LOGLEVEL: info  
      -ND_SESSIONTIMEOUT: 24h
      -ND_BASEURL: ""
      -PUID: 1024
      -PGID: 101
      -TZ: ${TZ}
    volumes:
      - "${CONFIGDIR}/navidrome:/data"
      - "music:/music:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.navidrome.rule=Host(`music.${DOMAINNAME}`) || Host(`navidrome.${DOMAINNAME}`)" 
      - "traefik.http.services.navidrome.loadbalancer.server.port=4533"
      - "traefik.http.routers.navidrome.entrypoints=https"
  
  picard:
    image: mikenye/picard:latest
    hostname: picard
    container_name: picard
    environment:
      -PUID: 1024
      -PGID: 101
      -TZ: ${TZ}
    ports:
      - "${PICARD_PORT}:5800"
    volumes:
      - ${CONFIGDIR}/picard:/config:rw
      - music:/storage:rw
    networks:
      - traefik_network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.picard.rule=Host(`picard.${DOMAINNAME}`)"
      - "traefik.http.services.picard.loadbalancer.server.port=5800"
      - "traefik.http.routers.picard.entrypoints=https"  

  filebrowser:
    hostname: filebrowser
    container_name: filebrowser
    image: filebrowser/filebrowser
    ports:
      - ${FILEBROWSER_PORT}:80
    volumes:
      - "${CONFIGDIR}/filebrowser/db:/config"
      - "${CONFIGDIR}/filebrowser/config/config.json:/.filebrowser.json"
      - "shows:/data/shares/TV Shows"
      - "movies:/data/shares/Movies"
      - "music:/data/shares/Music"
      - "books:/data/shares/Books"
      - "audiobooks:/data/shares/Audiobooks"
      - "downloads:/data/downloads/"
    environment:
      -TZ: ${TZ}

    networks:
      - traefik_network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filebrowser.rule=Host(`filebrowser.${DOMAINNAME}`)"
      - "traefik.http.services.filebrowser.loadbalancer.server.port=80"
      - "traefik.http.routers.filebrowser.entrypoints=https"

  jellyfin:
    container_name: jellyfin
    hostname: jellyfin
    image: jellyfin/jellyfin 
    environment: 
      - JELLYFIN_CACHE_DIR=/var/cache/jellyfin 
      - JELLYFIN_CONFIG_DIR=/etc/jellyfin 
      - JELLYFIN_DATA_DIR=/var/lib/jellyfin 
      - JELLYFIN_LOG_DIR=/var/log/jellyfin 
      - PUID=1024
      - PGID=101
      - TZ=${TZ}
    volumes: 
      - ${CONFIGDIR}/jellyfin/etc:/etc/jellyfin 
      - ${CONFIGDIR}/jellyfin/var-cache:/var/cache/jellyfin 
      - ${CONFIGDIR}/jellyfin/var-lib:/var/lib/jellyfin 
      - ${CONFIGDIR}/jellyfin/var-log:/var/log/jellyfin
      - /etc/timezone:/etc/timezone:ro
      - "shows:/mnt/shares/TV Shows"
      - "movies:/mnt/shares/Movies"
      - "music:/mnt/shares/Music"
      - "books:/mnt/shares/Books"
      - "audiobooks:/mnt/shares/Audiobooks"
      
    group_add: 
      - "109" 
    networks:
      - traefik_network
    ports:
      - ${JELLYFIN_PORT}:8096
      - ${JELLYFIN_PORT_2}:8920
    devices: # This might vary based on your use case
      - "/dev/dri/renderD128:/dev/dri/renderD128"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOMAINNAME}`)"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
      - "traefik.http.routers.jellyfin.entrypoints=https"
  
  filebot:
    container_name: filebot
    image: jlesage/filebot
    environment:
      -PUID: 1024
      -PGID: 101
      -TZ: ${TZ}
    ports:
      - "${FILEBOT_PORT}:5800"
    volumes:
      - ${CONFIGDIR}/filebot:/config:rw
      - shows:/storage/tvshows:rw
      - movies:/storage/movies:rw
    networks:
      - traefik_network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filebot.rule=Host(`filebot.${DOMAINNAME}`)"
      - "traefik.http.services.filebot.loadbalancer.server.port=5800"
      - "traefik.http.routers.filebot.entrypoints=https"  

  rdesktop:
    image: lscr.io/linuxserver/rdesktop:ubuntu-xfce
    container_name: rdesktop
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #optional
      - $CONFIGDIR/rdesktop:/config #optional
      - ./:/config/dockerroot
      # - /mnt/files:/mnt/files
      # - /mnt/books:/mnt/books
      # - /mnt/videos:/mnt/videos
#    network_mode: host 
    ports:
      - $RDESKTOPPORT:3389
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 #optional
    shm_size: "1gb" #optional
    restart: unless-stopped

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    hostname: audiobookshelf
    container_name: audiobookshelf
    environment:
      -PUID: 1024
      -PGID: 101
      -TZ: ${TZ}
    ports:
      - ${AUDIOBOOKSHELF_PORT}:80
    networks:
      - traefik_network
    volumes:
      - audiobooks:/audiobooks
      - podcasts:/podcasts
      - ${CONFIGDIR}/audiobookshelf/metadata:/metadata
      - ${CONFIGDIR}/audiobookshelf:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.audiobookshelf.rule=Host(`audiobookshelf.${DOMAINNAME}`)"
      - "traefik.http.services.audiobookshelf.loadbalancer.server.port=80"
      - "traefik.http.routers.audiobookshelf.entrypoints=https"  

  organizr:
    container_name: organizr
    hostname: organizr
    image: organizr/organizr:latest
    restart: unless-stopped
    ports:
      - 9944:80
    volumes:
      - ${CONFIGDIR}/organizr:/config
    environment:
      - PUID=1024
      - PGID=101
      - TZ=${TZ}
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.organizr.entrypoints=https"
      - "traefik.http.routers.organizr.rule=Host(`organizr.$DOMAINNAME`)"
      - "traefik.http.services.organizr.loadbalancer.server.port=80"