
networks:
  traefik_network:
    driver: bridge
    name: traefik_network
    external: true


volumes:
  audiobooks:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: '${AUDIOBOOKSDIR}'

  books:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: '${BOOKSDIR}'

  downloads:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: '${DOWNLOADSDIR}'

  tvdownloads:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: '${TVDOWNLOADSDIR}'
  
  moviedownloads:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: '${MOVIESDOWNLOADSDIR}'

  musicdownloads:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: '${MUSICDOWNLOADSDIR}'

  audiobookdownloads:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: '${AUDIOBOOKDOWNLOADSDIR}'

  bookdownloads:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: '${BOOKDOWNLOADSDIR}'

  movies:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: '${MOVIESDIR}'
  
  music:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: '${MUSICDIR}'

  photos:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: '${PHOTOSDIR}'

  shows:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: '${SHOWSDIR}'

  documents:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: '${DOCUMENTSDIR}'
  
  podcasts:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: '${PODCASTSDIR}'

services:
  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    environment:
      - PUID=1024
      - PGID=101
      - TZ=${TZ}
    networks:
      - traefik_network
    ports:
      - "${PORTAINER_PORT}:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${CONFIGDIR}/portainer:/data"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${DOMAINNAME}`)"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer.entrypoints=https"

  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    # devices: 
    #   - /dev/ttyUSB1
    #   - /dev/ttyUSB0
    networks:
      - traefik_network
    environment:
      - PUID=1024
      - PGID=101
      - TZ=${TZ}
    ports:
      - ${HOMEASSISTANT_PORT}:8123
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONFIGDIR}/homeassistant:/config
      - ${CONFIGDIR}/homeassistant/data:/mnt/Data
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homeassistant.rule=Host(`homeassistant.${DOMAINNAME}`) || Host(`ha.${DOMAINNAME}`)"
      - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"
      - "traefik.http.routers.homeassistant.entrypoints=https"

  whatsupdocker:
    image: fmartinou/whats-up-docker
    container_name: whatsupdocker
    networks:
      - traefik_network
    environment:
      - PUID=1024
      - PGID=101
      - TZ=${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONFIGDIR}/wud:/store
    ports:
      - ${WUD_PORT}:3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whatsupdocker.entrypoints=https"
      - "traefik.http.routers.whatsupdocker.rule=Host(`whatsup.${DOMAINNAME}`)"
      - "traefik.http.services.whatsupdocker.loadbalancer.server.port=3000"

  # excalidraw:
  #   image: kiliandeca/excalidraw
  #   container_name: excalidraw
  #   healthcheck:
  #     disable: true
  #   networks:
  #     - traefik_network
  #   ports:
  #     - "${EXCALIDRAW_PORT}:80" # Default port 80, can be modified
  #   environment:
  #     BACKEND_V2_GET_URL: http://localhost:8080/api/v2/scenes/
  #     BACKEND_V2_POST_URL: http://localhost:8080/api/v2/scenes/
  #     LIBRARY_URL: https://libraries.excalidraw.com
  #     LIBRARY_BACKEND: https://us-central1-excalidraw-room-persistence.cloudfunctions.net/libraries
  #     SOCKET_SERVER_URL: http://localhost:${EXCALIDRAW_STORAGE_PORT}/
  #     STORAGE_BACKEND: "http"
  #     HTTP_STORAGE_BACKEND_URL: "http://localhost:8080/api/v2"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.excalidraw.entrypoints=https"
  #     - "traefik.http.routers.excalidraw.rule=Host(`excalidraw.${DOMAINNAME}`)"
  #     - "traefik.http.services.excalidraw.loadbalancer.server.port=80"
  # excalidraw-storage:
  #   image: kiliandeca/excalidraw-storage-backend
  #   container_name: excalidraw-storage
  #   ports:
  #     - "${EXCALIDRAW_STORAGE_PORT}:8080"
  #   environment:
  #     STORAGE_URI: redis://excalidraw_redis:${EXCALIDRAW_REDIS_PORT}
  #   networks:
  #     - traefik_network
  # excalidraw-room:
  #   image: excalidraw/excalidraw-room
  #   container_name: excalidraw-room
  #   ports:
  #     - "${EXCALIDRAW_ROOM_PORT}:80"
  # excalidraw_redis:
  #   image: redis
  #   container_name: redis
  #   networks:
  #     - traefik_network
  #   ports:
  #     - "${EXCALIDRAW_REDIS_PORT}:6379"

  it-tools:
    ports:
      - "${ITTOOLS_PORT}:80"
    container_name: it-tools
    networks:
      - traefik_network
    environment:
      - PUID=1024
      - PGID=101
      - TZ=${TZ}
    image: corentinth/it-tools
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.it-tools.entrypoints=https"
      - "traefik.http.routers.it-tools.rule=Host(`it-tools.${DOMAINNAME}`)"
      - "traefik.http.services.it-tools.loadbalancer.server.port=80"


  guacd:
    container_name: guac_guacd
    image: guacamole/guacd
    networks:
      - traefik_network
    environment:
      - TZ=${TZ}
    restart: unless-stopped
    volumes:
      - ${CONFIGDIR}/guacamole/guacd/drive:/drive:rw
      - ${CONFIGDIR}/guacamole/guacd/record:/record:rw
  postgres:
    container_name: guac_postgres
    networks:
      - traefik_network
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PGDATA=/var/lib/postgresql/data/guacamole
      - POSTGRES_DB=guacamole_db
      - POSTGRES_PASSWORD='${GUACAMOLE_POSTGRESS_PASSWORD}'
      - POSTGRES_USER='${GUACAMOLE_POSTGRESS_USER}'
    image: postgres:15.2-alpine
    volumes:
      - ${CONFIGDIR}/guacamole/postgress/init:/docker-entrypoint-initdb.d:z
      - ${CONFIGDIR}/guacamole/postgress/data:/var/lib/postgresql/data:Z
  guacamole:
    container_name: guac_guacamole
    depends_on:
      - guacd
      - postgres
    environment:
      - TZ=${TZ}
      - GUACD_HOSTNAME=guacd
      - POSTGRESQL_DATABASE=guacamole_db
      - POSTGRESQL_HOSTNAME=postgres
      - POSTGRESQL_PASSWORD='${GUACAMOLE_POSTGRESS_PASSWORD}'
      - POSTGRESQL_USER='${GUACAMOLE_POSTGRESS_USER}'
    image: guacamole/guacamole
    links:
      - guacd
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.guacamole.entrypoints=https"
      - "traefik.http.routers.guacamole.rule=Host(`guacamole.$DOMAINNAME`)"
      - "traefik.http.routers.guacamole.middlewares=add-guacamole"
      - "traefik.http.middlewares.add-guacamole.addPrefix.prefix=/guacamole"
      - "traefik.http.services.guacamole.loadbalancer.server.port=8080"
    ports:
      - ${GUACAMOLE_PORT}:8080

  vaultwarden:
    image: vaultwarden/server:latest
    hostname: vaultwarden
    container_name: vaultwarden
    restart: unless-stopped
    networks:
      - traefik_network
    volumes:
      - ${CONFIGDIR}/vaultwarden/:/data
    # ports:
    #   - ${VAULTWARDEN_PORT}:80
    environment:
      - LOGIN_RATELIMIT_MAX_BURST=10
      - LOGIN_RATELIMIT_SECONDS=60
      - DOMAIN=https://$VW_PREFIX.$DOMAINNAME/
      - INVITATION_ORG_NAME=x
      - INVITATION_ALLOWED=${VW_SIGNUPS_ALLOWED}
      - ADMIN_TOKEN="${VW_ADMIN_TOKEN}"
      - SIGNUPS_ALLOWED=true
      - EMERGENCY_ACCESS_ALLOWED=true
      - SENDS_ALLOWED=true
      - WEB_VAULT_ENABLE=true
      - WEBSOCKET_ENABLED=${VW_WEBSOCKET_ENABLED}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vaultwarden.entrypoints=https"
      - "traefik.http.routers.vaultwarden.rule=Host(`$VW_PREFIX.$DOMAINNAME`)"
      - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"

  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    hostname: kavita
    networks:
      - traefik_network
    environment:
      - PUID=1024
      - PGID=101
      - TZ=${TZ}
    ports:
      - ${KAVITA_PORT}:5000
    volumes:
      - "${CONFIGDIR}/kavita:/config"
      - "books:/data:ro"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kavita.rule=Host(`read.${DOMAINNAME}`) || Host(`kavita.${DOMAINNAME}`)"
      - "traefik.http.services.kavita.loadbalancer.server.port=5000"
      - "traefik.http.routers.kavita.entrypoints=https"
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    hostname: navidrome
    networks:
      - traefik_network
    restart: unless-stopped
    ports:
      - ${NAVIDROME_PORT}:4533
    environment:
      -ND_SCANSCHEDULE: 1h
      -ND_LOGLEVEL: info  
      -ND_SESSIONTIMEOUT: 24h
      -ND_BASEURL: ""
      -PUID: 1024
      -PGID: 101
      -TZ: ${TZ}
    volumes:
      - "${CONFIGDIR}/navidrome:/data"
      - "music:/music:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.navidrome.rule=Host(`music.${DOMAINNAME}`) || Host(`navidrome.${DOMAINNAME}`)" 
      - "traefik.http.services.navidrome.loadbalancer.server.port=4533"
      - "traefik.http.routers.navidrome.entrypoints=https"
  
  picard:
    image: mikenye/picard:latest
    hostname: picard
    container_name: picard
    environment:
      -PUID: 1024
      -PGID: 101
      -TZ: ${TZ}
    ports:
      - "${PICARD_PORT}:5800"
    volumes:
      - ${CONFIGDIR}/picard:/config:rw
      - music:/storage:rw
    networks:
      - traefik_network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.picard.rule=Host(`picard.${DOMAINNAME}`)"
      - "traefik.http.services.picard.loadbalancer.server.port=5800"
      - "traefik.http.routers.picard.entrypoints=https"  

  filebrowser:
    hostname: filebrowser
    container_name: filebrowser
    image: hurlenko/filebrowser
    ports:
      - ${FILEBROWSER_PORT}:8080
    volumes:
      - "${CONFIGDIR}/filebrowser:/config"
      - "shows:/data/shares/TV Shows"
      - "movies:/data/shares/Movies"
      - "music:/data/shares/Music"
      - "books:/data/shares/Books"
      - "audiobooks:/data/shares/Audiobooks"
      - "tvdownloads:/data/downloads/TV Shows"
      - "moviedownloads:/data/downloads/Movies"
      - "musicdownloads:/data/downloads/Music"
      - "bookdownloads:/data/downloads/Books"
      - "audiobookdownloads:/data/downloads/Audiobooks"
    environment:
      -PUID: 1024
      -PGID: 101
      -FB_BASEURL: /filebrowser
      -TZ: ${TZ}
    networks:
      - traefik_network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filebrowser.rule=Host(`filebrowser.${DOMAINNAME}`)"
      - "traefik.http.services.filebrowser.loadbalancer.server.port=8080"
      - "traefik.http.routers.filebrowser.entrypoints=https"

  jellyfin:
    container_name: jellyfin
    hostname: jellyfin
    image: jellyfin/jellyfin 
    environment: 
      - JELLYFIN_CACHE_DIR=/var/cache/jellyfin 
      - JELLYFIN_CONFIG_DIR=/etc/jellyfin 
      - JELLYFIN_DATA_DIR=/var/lib/jellyfin 
      - JELLYFIN_LOG_DIR=/var/log/jellyfin 
      - PUID=1024
      - PGID=101
      - TZ=${TZ}
    volumes: 
      - ${CONFIGDIR}/jellyfin/etc:/etc/jellyfin 
      - ${CONFIGDIR}/jellyfin/var-cache:/var/cache/jellyfin 
      - ${CONFIGDIR}/jellyfin/var-lib:/var/lib/jellyfin 
      - ${CONFIGDIR}/jellyfin/var-log:/var/log/jellyfin 
      - /etc/timezone:/etc/timezone:ro
      - "shows:/mnt/shares/TV Shows"
      - "movies:/mnt/shares/Movies"
      - "music:/mnt/shares/Music"
      - "books:/mnt/shares/Books"
      - "audiobooks:/mnt/shares/Audiobooks"
      - "tvdownloads:/mnt/downloads/TV Shows"
      - "moviedownloads:/mnt/downloads/Movies"
      - "musicdownloads:/mnt/downloads/Music"
      - "bookdownloads:/mnt/downloads/Books"
      - "audiobookdownloads:/mnt/downloads/Audiobooks"
    group_add: 
      - "109" 
    networks:
      - traefik_network
    ports:
      - ${JELLYFIN_PORT}:8096
      - ${JELLYFIN_PORT_2}:892
    devices: # This might vary based on your use case
      - "/dev/dri/renderD128:/dev/dri/renderD128"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOMAINNAME}`)"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
      - "traefik.http.routers.jellyfin.entrypoints=https"
  
  filebot:
    container_name: filebot
    image: jlesage/filebot
    environment:
      -PUID: 1024
      -PGID: 101
      -TZ: ${TZ}
    ports:
      - "${FILEBOT_PORT}:5800"
    volumes:
      - ${CONFIGDIR}/filebot:/config:rw
      - shows:/storage/tvshows:rw
      - movies:/storage/movies:rw
    networks:
      - traefik_network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filebot.rule=Host(`filebot.${DOMAINNAME}`)"
      - "traefik.http.services.filebot.loadbalancer.server.port=5800"
      - "traefik.http.routers.filebot.entrypoints=https"  

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    hostname: audiobookshelf
    container_name: audiobookshelf
    environment:
      -PUID: 1024
      -PGID: 101
      -TZ: ${TZ}
    ports:
      - ${AUDIOBOOKSHELF_PORT}:80
    volumes:
      - audiobooks:/audiobooks
      - podcasts:/podcasts
      - ${CONFIGDIR}/audiobookshelf/metadata:/metadata
      - ${CONFIGDIR}/audiobookshelf:/config




  # reiverr: #Needs more work by devs
  #   image: ghcr.io/aleksilassila/reiverr:latest
  #   container_name: reiverr
  #   networks:
  #     - traefik_network
  #   environment:
  #     - PUID=1024
  #     - PGID=101
  #     - TZ=${TZ}
  #   ports:
  #     - ${REIVERR_PORT}:9494
  #   volumes:
  #     - ${CONFIGDIR}/reiverr:/config
  #   restart: unless-stopped
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.reiverr.entrypoints=https"
  #     - "traefik.http.routers.reiverr.rule=Host(`reiverr.$DOMAINNAME`)"
  #     - "traefik.http.services.reiverr.loadbalancer.server.port=9494"

  # organizr: #Couldn't get working
  #   container_name: organizr
  #   hostname: organizr
  #   image: organizr/organizr:latest
  #   restart: unless-stopped
  #   ports:
  #     - ${ORGANIZR_PORT}:80
  #   volumes:
  #     - ${CONFIGDIR}/organizr:/config
  #   environment:
  #     - PUID=1024
  #     - PGID=101
  #     - TZ=${TZ}
  #   networks:
  #     - traefik_network
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.organizr.entrypoints=https"
  #     - "traefik.http.routers.organizr.rule=Host(`organizr.$DOMAINNAME`)"
  #     - "traefik.http.services.organizr.loadbalancer.server.port=80"

  # watchtower: # Whatsupdocker is better
  #   image: containrrr/watchtower
  #   container_name: watchtower
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   networks:
  #     - traefik_network
  #   restart: unless-stopped

