[[servers]]
host = "openldap"
port = 389
use_ssl = false
start_tls = false
ssl_skip_verify = true
bind_dn = "cn=admin,${LDAP_BASE_DN}"
bind_password = "${LDAP_ADMIN_PASSWORD}"
search_filter = "(uid=%s)"
search_base_dns = ["${LDAP_BASE_DN}"]

[servers.attributes]
name = "displayName"
surname = "sn"
username = "uid"
member_of = "memberOf"
email =  "email"

[[servers.group_mappings]]
group_dn = "cn=admins,ou=groups,${LDAP_BASE_DN}"
org_role = "Admin"
grafana_admin = true # Available in Grafana v5.3 and above

[[servers.group_mappings]]
group_dn = "cn=everybody,ou=groups,${LDAP_BASE_DN}"
org_role = "Viewer"